### ISSUE TITLE
Support dependency renames

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cargo-tally#22]
```toml
[dependencies]
rpc = { package = "tarpc-lib", version = "0.1" }
```

Blocked on https://github.com/rust-lang/crates.io/issues/1539.
