### ISSUE TITLE
Support Cargo's "namespaced features"

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cargo-tally#55]
Reference:

- https://rust-lang.github.io/rfcs/3143-cargo-weak-namespaced-features.html
- https://github.com/rust-lang/cargo/issues/5565

Example:

```toml
[dependencies]
ravif = { version = "0.6.3", optional = true }
rgb = { version = "0.8.25", optional = true }

[features]
avif = ["dep:ravif", "dep:rgb"]
```
