### ISSUE TITLE
Support Cargo's "weak dependency features"

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cargo-tally#56]
Reference:

- https://rust-lang.github.io/rfcs/3143-cargo-weak-namespaced-features.html
- https://github.com/rust-lang/cargo/issues/8832

Example:

```toml
[dependencies]
serde = { version = "1.0", optional=true, default-features = false }

[features]
std = ["serde?/std"]
```
